name: Integration tests and flake8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vm-job:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio:6.0.0
        env:
          MINIO_ACCESS_KEY: administrator
          MINIO_SECRET_KEY: administrato
        ports: 
          - 9000:9000

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: integration tests
    - run: pytest -v tests/tests.py
      env:
        MINIO_TEST_CONNECTION: localhost:9000
        MINIO_TEST_ACCESS_KEY: administrator
        MINIO_TEST_SECRET_KEY: administrator
